version: "3"
services:
  course:
    container_name: course-rate
    image: course-rate
    build:
      context:
        CourseRate
      dockerfile: Dockerfile
    depends_on:
      - dbpostgresql
    ports:
    - "8081:8081"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  weather:
    container_name: weather-tempreture
    image: weather-tempreture
    build:
      context:
        WeatherService
      dockerfile: Dockerfile
    ports:
    - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  prediction:
    container_name: predict-weather
    image: predict-weather
    build:
      context: PredictWeather
      dockerfile: Dockerfile
    depends_on:
      - course
      - weather
    ports:
    - "8080:8080"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: tiger20111
      POSTGRES_PASSWORD: qwerty
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    entrypoint:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=qwerty
    depends_on:
      - dbpostgresql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
