version: "3"
services:
  course:
    container_name: course-rate
    image: course-rate
    build:
      context:
        CourseRate
      dockerfile: Dockerfile
    depends_on:
      - dbpostgresql
    ports:
    - "8081:8081"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  weather:
    container_name: weather-tempreture
    image: weather-tempreture
    build:
      context:
        WeatherService
      dockerfile: Dockerfile
    ports:
    - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  prediction:
    container_name: predict-weather
    image: predict-weather
    build:
      context: PredictWeather
      dockerfile: Dockerfile
    depends_on:
      - course
      - weather
    ports:
    - "8080:8080"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: tiger20111
      POSTGRES_PASSWORD: qwerty
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - dbpostgresql
    ports:
      - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

  grafana:
    image: grafana/grafana
    ports:
      - "3030:3000"
    env_file:
      - config
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9080:9090"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

