version: "3"
services:
  course:
    container_name: course-rate
    image: course-rate
    build:
      context:
        CourseRate
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  weather:
    container_name: weather-tempreture
    image: weather-tempreture
    build:
      context:
        WeatherService
      dockerfile: Dockerfile
    ports:
    - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  prediction:
    container_name: predict-weather
    image: predict-weather
    build:
      context: PredictWeather
      dockerfile: Dockerfile
    depends_on:
      - course
      - weather
    ports:
    - "8080:8080"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7



networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
