version: "3"
services:
  course:
    container_name: course-rate
    image: course-rate
    build: .
    ports:
    - "8081:8081"
  weather:
    container_name: weather-tempreture
    image: weather-tempreture
    build: .
    ports:
    - "8082:8082"
  prediction:
    container_name: predict-weather
    image: predict-weather
    build: .
    ports:
    - "8083:8083"