global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'dollar_rate_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['course-rate:8081']
  - job_name: 'predict_weather_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['predict-weather:8080']
  - job_name: 'weather_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['weather-tempreture:8082']