version: "3"
services:
  course:
    container_name: course-rate
    image: course-rate
    build:
      context:
        ./CourseRate
      dockerfile: Dockerfile
    depends_on:
      - dbpostgresql
    ports:
      - "8081:8081"

  weather:
    container_name: weather-tempreture
    image: weather-tempreture
    build:
      context:
        ./WeatherService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  prediction:
    container_name: predict-weather
    image: predict-weather
    build:
      context: ./PredictWeather
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: tiger20111
      POSTGRES_PASSWORD: qwerty

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - dbpostgresql
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

