version: '3'
services:
  weather:
    image: weather-tempreture
    container_name: weather-tempreture
    build:
      context: weather
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  course:
    image: course-rate
    container_name: course-rate
    build:
      context: rate
      dockerfile: Dockerfile
    depends_on:
      - dbpostgresql
    ports:
      - "8081:8081"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: tiger20111
      POSTGRES_PASSWORD: qwerty
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16