- hosts: prediction-server
  remote_user: edumfti
  become: yes

  vars:
    ansible_become_user: root
    ansible_become_password: aNSHaPi

  tasks:
    - name: Delete last version of directoreis
      shell: rm -rf ./edu/protsenko

    - name: Create a folders for prediction service
      shell: mkdir -p edu/protsenko && mkdir -p edu/protsenko/prediction && mkdir -p edu/protsenko/prediction/target

    - name: cp prediction service
      copy:
        src: ../PredictWeather/target/PredictWeather-0.1.0.jar
        dest: edu/protsenko/prediction/target

    - name: Copy Dockerfile for prediction service
      copy:
        src: ../PredictWeather/Dockerfile
        dest: edu/protsenko/prediction

    - name: Copy docker-compose-prediction file
      copy:
        src: ./docker-compose-prediction.yml
        dest: edu/protsenko/prediction

    - name: Run the docker-compose-prediction file
      shell: sudo docker-compose -f ./edu/protsenko/prediction/docker-compose-prediction.yml up -d