- hosts: rate_weather-server
  remote_user: mftiedu
  become: yes

  vars:
    ansible_become_user: root
    ansible_become_password: cHONtic

  tasks:
    - name: Delete last version of directoreis and create a new one for rate and weather services
      shell: rm -rf ./edu/protsenko && mkdir -p edu/protsenko/rate && mkdir -p edu/protsenko/weather && edu/protsenko/rate/target && edu/protsenko/weather/rate

    - name: Copy rate service
      copy:
        src: ../CourseRate/target/CourseRate-0.1.0.jar
        dest: edu/protsenko/rate/target

    - name: Copy weather service
      copy:
        src: ../WeatherService/target/WeatherService-0.1.0.jar
        dest: edu/protsenko/weather/target

    - name: Copy Dockerfile for weather service
      copy:
        src: ../WeatherService/Dockerfile
        dest: edu/protsenko/weather

    - name: Copy Dockerfile for rate service
      copy:
        src: ../CourseRate/Dockerfile
        dest: edu/protsenko/rate

    - name: Load image for rate service
      docker_image:
        name: course-rate
        build:
          path: ./edu/protsenko/rate
          pull: yes
        source: build

    - name: Load image for weather service
      docker_image:
        name: weather-tempreture
        build:
          path: ./edu/protsenko/weather
          pull: yes
        source: build

    - name: Copy docker-compose-rate-weather file
      copy:
        src: ./docker-compose-rate-weather.yml
        dest: edu/protsenko/

    - name: Run the docker-compose-rate-weather file
      shell: sudo docker-compose -f ./edu/protsenko/docker-compose-rate-weather.yml up -d